INSERT INTO Bid (MyRepairId, MYREPAIRERID, PRICE, ACCEPTED, ELIGIBLE, DISCRIMINATOR)
VALUES (1, 4, 2000, FALSE, TRUE, 'FixedBid');
INSERT INTO Bid (MyRepairId, MYREPAIRERID, PRICE, ACCEPTED, ELIGIBLE, DISCRIMINATOR)
VALUES (2, 4, 1000, FALSE, TRUE, 'FixedBid');
INSERT INTO Bid (MyRepairId, MYREPAIRERID, PRICE, ACCEPTED, ELIGIBLE, DISCRIMINATOR)
VALUES (6, 4, 1500, FALSE, TRUE, 'FixedBid');
