INSERT INTO Item (ProductName, Brand, Category) VALUES ('G 6510 SC BW', 'Miele', 'Vaatwasser');
INSERT INTO Item (ProductName, Brand, Category) VALUES ('SN25L280EU', 'Siemens', 'Vaatwasser');
INSERT INTO Item (ProductName, Brand, Category) VALUES ('F55033W0', 'AEG', 'Vaatwasser');
INSERT INTO Item (ProductName, Brand, Category) VALUES ('B36753', 'Bosch', 'Vaatwasser');
INSERT INTO Item (ProductName, Brand, Category) VALUES ('Chromebook XE303C12', 'Samsung', 'Laptop');
INSERT INTO Item (ProductName, Brand, Category) VALUES ('N76VB-T4038H', 'Asus', 'Laptop');
INSERT INTO Item (ProductName, Brand, Category) VALUES ('MacBook Air', 'Apple', 'Laptop');
INSERT INTO Item (ProductName, Brand, Category) VALUES ('Galaxy Tab 3 10.1 WiFi', 'Samsung', 'Tablet');
INSERT INTO Item (ProductName, Brand, Category) VALUES ('iPad mini 2 16GB WiFi', 'Apple', 'Tablet');
INSERT INTO Item (ProductName, Brand, Category) VALUES ('One', 'HTC', 'Smartphone');
INSERT INTO Item (ProductName, Brand, Category) VALUES ('S4 Mini i9195', 'Samsung', 'Smartphone');
INSERT INTO Item (ProductName, Brand, Category) VALUES ('Nexus 5 16GB', 'LG', 'Smartphone');
